name: tests-ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install
      run: make install

    - name: testing
      run: make tests

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
